begin;
create extension if not exists pgtap with schema extensions;
set local search_path = extensions, public, pg_catalog;
select plan(14);
select has_table('telemetry', 'session_pr_context_events', 'declared context facts exist');
select has_table('github', 'pr_context_verifications', 'GitHub checks are separate observations');
select ok(has_table_privilege('sherlock_normalizer', 'telemetry.session_pr_context_events', 'insert'), 'normalizer may append declared facts');
select ok(not has_table_privilege('sherlock_normalizer', 'telemetry.session_pr_context_events', 'update'), 'normalizer cannot edit history');
select ok(not has_table_privilege('sherlock_normalizer', 'telemetry.session_pr_context_events', 'delete'), 'normalizer cannot erase links or corrections');
select ok(has_table_privilege('sherlock_processor', 'github.pr_context_verifications', 'insert'), 'worker may append checks');
select ok(not has_table_privilege('sherlock_processor', 'github.pr_context_verifications', 'update'), 'worker cannot rewrite checks');
select ok(not has_table_privilege('sherlock_processor', 'github.pr_context_verifications', 'delete'), 'worker cannot erase checks');
select ok(has_table_privilege('sherlock_reader', 'telemetry.session_pr_context_events', 'select') and has_table_privilege('sherlock_reader', 'github.pr_context_verifications', 'select'), 'dashboard reader has explicit read grants');
select ok(not has_table_privilege('anon', 'telemetry.session_pr_context_events', 'select') and not has_table_privilege('authenticated', 'github.pr_context_verifications', 'select'), 'public Data API cannot read context');
select ok(not exists (select 1 from pg_constraint where conrelid = 'telemetry.session_pr_context_events'::regclass and confrelid = 'telemetry.sessions'::regclass), 'context may arrive before its native session');
select ok(exists (select 1 from pg_constraint where conrelid = 'telemetry.session_pr_context_events'::regclass and confrelid = 'telemetry.native_records'::regclass), 'every fact preserves native source provenance');
select ok(exists (select 1 from pg_trigger where tgrelid = 'telemetry.sessions'::regclass and tgname = 'guard_session_provider_collision' and not tgisinternal), 'old and new native writers refuse provider collision');
select ok(pg_get_functiondef('processing.enqueue_telemetry_job()'::regprocedure) like '%sherlock.pr-context.v1%', 'queue dispatch uses independent sidecar version');
select * from finish();
rollback;
